# -*- coding: utf-8 -*-
"""New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1it2teTqddtoykOCNQtNUYkp5ICYn5fkS

#List
"""

n= [10, 15, 6, 8, 9]
print("The numbers are: ", n)